/*
James Liang
Lab 14
*/

SET SERVEROUTPUT ON;
VARIABLE BALANCE_NUM NUMBER;
CREATE TABLE INVOICES_DUE AS (SELECT i.INVOICE_NUMBER, v.VENDOR_NAME, i.INVOICE_TOTAL, i.PAYMENT_TOTAL, i.CREDIT_TOTAL FROM AP.INVOICES i JOIN AP.VENDORS v ON  i.VENDOR_ID = v.VENDOR_ID);

--1.
DECLARE
    CURSOR I_CURSOR IS SELECT i.INVOICE_NUMBER, v.VENDOR_NAME, i.INVOICE_TOTAL, i.PAYMENT_TOTAL, i.CREDIT_TOTAL, (i.INVOICE_TOTAL - i.PAYMENT_TOTAL - i.CREDIT_TOTAL) AS BAL_DUE FROM AP.INVOICES i JOIN AP.VENDORS v ON  i.VENDOR_ID = v.VENDOR_ID ORDER BY 6 DESC;
    I_ROW INVOICES_DUE%ROWTYPE;
    BALANCE_DUE VARCHAR2(50);
BEGIN
    FOR I_ROW IN I_CURSOR LOOP
    IF (I_ROW.INVOICE_TOTAL - I_ROW.PAYMENT_TOTAL - I_ROW.CREDIT_TOTAL >= 5000) THEN
    BALANCE_DUE := TO_CHAR(I_ROW.INVOICE_TOTAL - I_ROW.PAYMENT_TOTAL - I_ROW.CREDIT_TOTAL, '$999,999.99');
    DBMS_OUTPUT.PUT_LINE(BALANCE_DUE || ' ' || I_ROW.INVOICE_NUMBER || ' ' || I_ROW.VENDOR_NAME);
    END IF;
    END LOOP;
END;
/

--2.
DECLARE
    CURSOR I_CURSOR IS SELECT i.INVOICE_NUMBER, v.VENDOR_NAME, i.INVOICE_TOTAL, i.PAYMENT_TOTAL, i.CREDIT_TOTAL, (i.INVOICE_TOTAL - i.PAYMENT_TOTAL - i.CREDIT_TOTAL) AS BAL_DUE FROM AP.INVOICES i JOIN AP.VENDORS v ON  i.VENDOR_ID = v.VENDOR_ID ORDER BY 6 DESC;
    I_ROW INVOICES_DUE%ROWTYPE;
    BALANCE_DUE VARCHAR2(50);
BEGIN
    :BALANCE_NUM := &BALANCE_NUMBER;
    FOR I_ROW IN I_CURSOR LOOP
    IF (I_ROW.INVOICE_TOTAL - I_ROW.PAYMENT_TOTAL - I_ROW.CREDIT_TOTAL >= :BALANCE_NUM) THEN
    BALANCE_DUE := TO_CHAR(I_ROW.INVOICE_TOTAL - I_ROW.PAYMENT_TOTAL - I_ROW.CREDIT_TOTAL, '$999,999.99');
    DBMS_OUTPUT.PUT_LINE(BALANCE_DUE || ' ' || I_ROW.INVOICE_NUMBER || ' ' || I_ROW.VENDOR_NAME);
    END IF;
    END LOOP;
END;
/
