/*
James Liang
Lab 15
*/

CREATE TABLE EMPLOYEE_COPY AS SELECT * FROM STUDENT.EMPLOYEE;
SET SERVEROUTPUT ON;

--1.
CREATE OR REPLACE TRIGGER Lab15Trigger1
AFTER DELETE ON EMPLOYEE_COPY
BEGIN
IF DELETING THEN
    INSERT INTO EMPLOYEE_COPY VALUES (1, 'Sally', '1000000', 'Accountant');
END IF;
END;
/

DELETE FROM EMPLOYEE_COPY WHERE EMPLOYEE_ID > 0;

ALTER TRIGGER Lab15Trigger1 DISABLE;

--2.
CREATE OR REPLACE TRIGGER Lab15Trigger2
BEFORE DELETE ON EMPLOYEE_COPY
DECLARE
    ID EMPLOYEE_COPY.EMPLOYEE_ID%TYPE;
BEGIN
    SELECT COUNT(*) INTO ID FROM EMPLOYEE_COPY;
IF ID < 20 THEN
    RAISE_APPLICATION_ERROR(-20000,'SQL Error: ORA-20101: At least 20 rows in employee_copy table');
END IF;
END;
/

DELETE FROM EMPLOYEE_COPY WHERE EMPLOYEE_ID = 1;