/*
James Liang
Lab 11
*/

--3.
CREATE TABLE MEMBERS(
MEMBER_ID INT ,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
ADDRESS VARCHAR(200),
CITY VARCHAR(50),
STATE VARCHAR(50),
PHONE VARCHAR(20),
CONSTRAINT MEMBERS_PK PRIMARY KEY (MEMBER_ID));

CREATE TABLE GROUPS(
GROUP_ID INT,
GROUP_NAME VARCHAR(50),
CONSTRAINT GROUPS_PK PRIMARY KEY (GROUP_ID));

CREATE TABLE MEMBERS_GROUPS(
MEMBER_ID INT,
GROUP_ID INT,
CONSTRAINT MEMBERS_GROUPS_PK PRIMARY KEY (MEMBER_ID, GROUP_ID),
CONSTRAINT MEMBERS_GROUPS_FK1 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
CONSTRAINT MEMBERS_GROUPS_FK2 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID));

--4.
INSERT INTO MEMBERS
VALUES (1, 'John', 'Smith', '334 Valencia St.', 'San Francisco', 
'CA', '415-942-1901');
INSERT INTO MEMBERS
VALUES (2, 'Jane', 'Doe', '872 Chetwood St.', 'Oakland', 'CA', 
'510-123-4567');

INSERT INTO GROUPS
VALUES (1, 'Book Club');
INSERT INTO GROUPS
VALUES (2, 'Bicycle Coalition');

INSERT INTO MEMBERS_GROUPS
VALUES (1, 2);
INSERT INTO MEMBERS_GROUPS
VALUES (2, 1);
INSERT INTO MEMBERS_GROUPS
VALUES (2, 2);

SELECT m.LAST_NAME, m.FIRST_NAME, g.GROUP_NAME
FROM MEMBERS m
INNER JOIN MEMBERS_GROUPS mg on m.MEMBER_ID = mg.MEMBER_ID
INNER JOIN GROUPS g on mg.GROUP_ID = g.GROUP_ID;

--5.
CREATE SEQUENCE MEMBERS_SEQUENCE START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE GROUPS_SEQUENCE START WITH 3 INCREMENT BY 1;

--6.
INSERT INTO GROUPS(GROUP_ID, GROUP_NAME) VALUES(GROUPS_SEQUENCE.NEXTVAL, 'Sailing Club');
SELECT * FROM GROUPS;

--7.
ALTER TABLE MEMBERS ADD (ANNUAL_DUES DECIMAL(5, 2) DEFAULT 52.50, PAYMENT_DATE DATE);

--8.
ALTER TABLE GROUPS ADD UNIQUE(GROUP_NAME);
INSERT INTO GROUPS(GROUP_ID, GROUP_NAME) VALUES(GROUPS_SEQUENCE.NEXTVAL, 'Sailing Club');
