/*
James Liang
Lab 5
*/

--1.
SELECT COUNT(*) AS "Number of Invoices" FROM AP.INVOICES;

--2.
SELECT COUNT(PAYMENT_DATE) AS "Number of Valid Payment Dates" FROM AP.INVOICES WHERE PAYMENT_DATE IS NOT NULL;

--3.
SELECT COUNT(*) - COUNT(PAYMENT_DATE) AS "Number of Null Payment Dates" FROM AP.INVOICES WHERE PAYMENT_DATE IS NULL;

--4.
SELECT DISTINCT PAYMENT_DATE FROM AP.INVOICES ORDER BY PAYMENT_DATE;

--5.
SELECT COUNT(DISTINCT PAYMENT_DATE) AS "Number of Diff. Payment Dates" FROM AP.INVOICES;

--6.
SELECT TO_CHAR(SUM(INVOICE_TOTAL), '$999,999.99') AS "Total Invoice Amount" FROM AP.INVOICES;

--7.
SELECT ROUND(AVG(INVOICE_TOTAL),3) AS "Average Invoice Amount" FROM AP.INVOICES;

--8.
SELECT FLOOR(AVG(INVOICE_TOTAL)) AS "Average Invoice Amount" FROM AP.INVOICES;

--9.
SELECT MIN(INVOICE_TOTAL) AS "Lowest Invoice Total", MAX(INVOICE_TOTAL) AS "Highest Invoice Total" FROM AP.INVOICES; 

--10.
SELECT TO_CHAR(MIN(INVOICE_TOTAL),'$999,999.99') AS "Lowest Invoice Total", TO_CHAR(MAX(INVOICE_TOTAL),'$999,999.99') AS "Highest Invoice Total" FROM AP.INVOICES;

--11.
SELECT MAX(VENDOR_NAME) AS "Last Vendor" FROM AP.VENDORS;

--12.
SELECT MIN(INVOICE_DATE) FROM AP.INVOICES;

--13.
SELECT INVOICE_DATE, COUNT(*) AS "Invoices per Date" FROM AP.INVOICES GROUP BY INVOICE_DATE ORDER BY INVOICE_DATE;

--14.
SELECT INVOICE_TOTAL, COUNT(*) AS "Invoices Less Than $10.00" FROM AP.INVOICES WHERE INVOICE_TOTAL < 10 GROUP BY INVOICE_TOTAL ORDER BY INVOICE_TOTAL;

--15.
SELECT VENDOR_STATE, COUNT(*) AS "Vendors per State" FROM AP.VENDORS GROUP BY VENDOR_STATE ORDER BY VENDOR_STATE;

--16.
SELECT VENDOR_STATE, COUNT(*) AS "Vendors per State" FROM AP.VENDORS GROUP BY VENDOR_STATE HAVING COUNT(*) >= 3 ORDER BY COUNT(*) DESC;

--17.
SELECT TERMS_ID, COUNT(*) AS "Number in Terms Id Category" FROM AP.INVOICES GROUP BY TERMS_ID ORDER BY TERMS_ID;

--18.
SELECT INVOICE_DATE, COUNT(*) AS "Invoices per Date" FROM AP.INVOICES WHERE INVOICE_DATE >= '01-JUN-14' AND INVOICE_DATE < '01-JUL-14' GROUP BY INVOICE_DATE ORDER BY INVOICE_DATE ASC;

--19.
SELECT INVOICE_DATE, COUNT(*) AS "Invoices per Date" FROM AP.INVOICES GROUP BY INVOICE_DATE HAVING INVOICE_DATE >= '01-JUN-14' AND INVOICE_DATE < '01-JUL-14' ORDER BY INVOICE_DATE ASC;

--20.
SELECT INVOICE_DUE_DATE - INVOICE_DATE AS "Difference in Days", COUNT(INVOICE_DUE_DATE - INVOICE_DATE) AS "How Many?" FROM AP.INVOICES GROUP BY INVOICE_DUE_DATE - INVOICE_DATE ORDER BY INVOICE_DUE_DATE - INVOICE_DATE DESC;
