/*
James Liang
Lab 6
*/

--1.
SELECT TO_CHAR(AVG(COURSE_FEE), '$999,999.99') AS "Average Cost per Course" FROM STUDENT.COURSE_REVENUE;

--2.
SELECT STUDENT_ID, STATE
FROM STUDENT.STUDENT s
JOIN STUDENT.ZIPCODE z ON s.ZIP=z.ZIP
ORDER BY STUDENT_ID
FETCH FIRST 10 ROWS ONLY;

--3.
SELECT STUDENT_ID, STATE
FROM STUDENT.STUDENT s, STUDENT.ZIPCODE z
WHERE s.ZIP=z.ZIP
ORDER BY STUDENT_ID
FETCH FIRST 10 ROWS ONLY;

--4.
SELECT s.STUDENT_ID, z.CITY || ', '|| z.STATE AS "City, State"
FROM STUDENT.STUDENT s
JOIN STUDENT.ZIPCODE z ON s.ZIP=z.ZIP
ORDER BY s.STUDENT_ID
FETCH FIRST 10 ROWS ONLY;

--5.
SELECT n.DESCRIPTION AS "Course Description", 
TO_CHAR(r.REVENUE, '$999,999') AS "Total Revenue",
TO_CHAR(ROUND(r.revenue/r.NUM_OF_SECTIONS, 2),'$999,999.99') AS "Revenue per section taught"
FROM STUDENT.COURSE n
JOIN STUDENT.COURSE_REVENUE r ON n.COURSE_NO=r.COURSE_NO
ORDER BY "Total Revenue" DESC;

--6.
SELECT i.INSTRUCTOR_ID, i.FIRST_NAME, i.LAST_NAME, n.NUM_OF_CLASSES, n.NUM_OF_STUDENTS
FROM STUDENT.INSTRUCTOR i
JOIN STUDENT.INSTRUCTOR_SUMMARY n ON i.INSTRUCTOR_ID=n.INSTRUCTOR_ID
WHERE n.NUM_OF_CLASSES > 0
ORDER BY n.NUM_OF_CLASSES DESC, n.NUM_OF_STUDENTS DESC;

--7.
SELECT g.GRADE_TYPE_CODE, g.DESCRIPTION, ROUND(AVG(n.NUMERIC_GRADE),2) AS "AVERAGE GRADE"
FROM STUDENT.GRADE_TYPE g
JOIN STUDENT.GRADE n ON g.GRADE_TYPE_CODE = n.GRADE_TYPE_CODE
GROUP BY g.GRADE_TYPE_CODE, g.DESCRIPTION
ORDER BY g.GRADE_TYPE_CODE;

--8.
SELECT i.INSTRUCTOR_ID, i.LAST_NAME, TO_CHAR(r.REVENUE/r.NUM_OF_STUDENTS, '$999,999.00') AS "Revenue per student"
FROM STUDENT.INSTRUCTOR_SUMMARY r
JOIN STUDENT.INSTRUCTOR i ON i.INSTRUCTOR_ID=r.INSTRUCTOR_ID
WHERE r.REVENUE > 0
ORDER BY "Revenue per student" DESC;

--9.
SELECT i.INVOICE_ID, v.VENDOR_NAME
FROM AP.INVOICES i
JOIN AP.VENDORS v ON i.VENDOR_ID=v.VENDOR_ID
ORDER BY INVOICE_ID ASC
FETCH FIRST 10 ROWS ONLY;

--10.
SELECT DISTINCT VENDOR_NAME
FROM AP.VENDORS
ORDER BY VENDOR_NAME
FETCH FIRST 10 ROWS ONLY;

--11.
SELECT INVOICE_ID, v.VENDOR_NAME
FROM AP.INVOICES i
JOIN AP.VENDORS v ON i.VENDOR_ID=v.VENDOR_ID
WHERE REGEXP_LIKE(v.vendor_name, '^[H-L]');

--12.
SELECT MIN(PAYMENT_DATE) AS "Earliest Payment Date", MAX(PAYMENT_DATE) AS "Latest Payment Date",
TO_DATE(MIN(PAYMENT_DATE), 'DD-MON-YY') + ((TO_DATE(MAX(PAYMENT_DATE), 'DD-MON-YY') - TO_DATE(MIN(PAYMENT_DATE), 'DD-MON-YY'))/2) AS "Date in Between"
FROM AP.INVOICES;

--13.
SELECT INVOICE_NUMBER,
REPLACE(INVOICE_NUMBER, '-','') AS "No Dashes"
FROM AP.INVOICES
ORDER BY INVOICE_NUMBER
FETCH FIRST 10 ROWS ONLY;

--14.
SELECT VENDOR_NAME
FROM AP.VENDORS
WHERE VENDOR_NAME LIKE('%Inc') OR VENDOR_NAME LIKE ('%Inc.');

--15.
SELECT VENDOR_NAME, DECODE(VENDOR_ADDRESS1, 'NULL', NULL, VENDOR_ADDRESS1) || ' ' || DECODE(VENDOR_ADDRESS2, 'NULL', NULL, VENDOR_ADDRESS2) || ' ' || vendor_city || ', ' || vendor_state || ' ' || vendor_zip_code AS "Complete Address"
FROM AP.VENDORS
WHERE VENDOR_NAME LIKE('P%')
ORDER BY VENDOR_NAME;
