/*
James Liang
Lab 8
*/

--1.
SELECT MIN(COST) AS COST FROM STUDENT.COURSE;

--2.
SELECT DISTINCT COST FROM STUDENT.COURSE WHERE COST > (SELECT MIN(COST) FROM STUDENT.COURSE) AND COST < (SELECT MAX(COST) FROM STUDENT.COURSE);

--3.
SELECT DISTINCT COST FROM STUDENT.COURSE WHERE COST > (SELECT AVG(COST) FROM STUDENT.COURSE);

--4.
SELECT MIN(ENROLL_DATE) AS "Earliest Enrollment Date" FROM STUDENT.ENROLLMENT;

--5.
SELECT MIN(ENROLL_DATE) + 30 AS "Earliest Date plus 30" FROM STUDENT.ENROLLMENT;

--6.
SELECT VENDOR_NAME, INVOICE_NUMBER, INVOICE_TOTAL FROM AP.INVOICES i INNER JOIN AP.VENDORS v ON v.VENDOR_ID = i.VENDOR_ID WHERE INVOICE_TOTAL < (SELECT MAX(INVOICE_TOTAL) FROM AP.INVOICES WHERE VENDOR_ID = 123) ORDER BY VENDOR_NAME FETCH FIRST 10 ROWS ONLY;

--7.
SELECT VENDOR_ID, VENDOR_NAME, VENDOR_STATE FROM AP.VENDORS WHERE VENDOR_ID NOT IN (SELECT VENDOR_ID FROM AP.INVOICES) ORDER BY VENDOR_ID FETCH FIRST 10 ROWS ONLY;

--8.
SELECT COST FROM STUDENT.COURSE WHERE COST > (SELECT MIN(COST) FROM STUDENT.COURSE) ORDER BY COST;

--9.
SELECT VENDOR_ID, INVOICE_NUMBER, INVOICE_TOTAL FROM AP.INVOICES i WHERE INVOICE_TOTAL > (SELECT AVG(INVOICE_TOTAL) FROM AP.INVOICES v WHERE v.VENDOR_ID = i.VENDOR_ID) ORDER BY VENDOR_ID;

--10.
SELECT v.VENDOR_ID, v.VENDOR_NAME, i.INVOICE_ID FROM AP.VENDORS v INNER JOIN AP.INVOICES i ON v.VENDOR_ID = I.VENDOR_ID;

--11.
SELECT v.VENDOR_NAME, COUNT(i.INVOICE_ID) FROM AP. VENDORS v INNER JOIN AP.INVOICES i ON v.VENDOR_ID = i.VENDOR_ID GROUP BY v.VENDOR_NAME ORDER BY VENDOR_NAME;

--12.
SELECT VENDOR_CONTACT_LAST_NAME, VENDOR_CONTACT_FIRST_NAME, VENDOR_STATE FROM AP.VENDORS WHERE (VENDOR_STATE = 'CA' OR VENDOR_STATE = 'NJ') AND (LENGTH(VENDOR_CONTACT_LAST_NAME) > LENGTH(VENDOR_CONTACT_FIRST_NAME)) ORDER BY VENDOR_CONTACT_LAST_NAME;

--13.
SELECT VENDOR_ID, VENDOR_NAME FROM AP.VENDORS WHERE INSTR(VENDOR_NAME, '''') > 0;

--14.
SELECT LAST_NAME, DEPARTMENT_NAME FROM HR.EMPLOYEES e FULL OUTER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID ORDER BY DEPARTMENT_NAME FETCH FIRST 10 ROWS ONLY;

--15.
SELECT LAST_NAME, DEPARTMENT_NAME FROM HR.EMPLOYEES e FULL OUTER JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID WHERE DEPARTMENT_NAME IS NULL ORDER BY DEPARTMENT_NAME;
