/*
James Liang
Lab 9
*/

--1.
SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT, HIRE_DATE FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE 'J%' AND COMMISSION_PCT >= 0.1 ORDER BY FIRST_NAME;

--2.
SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT, HIRE_DATE FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE 'J%' AND COMMISSION_PCT >= 0.1 AND LAST_NAME LIKE '%o%' AND HIRE_DATE >= '01-JAN-2006' ORDER BY FIRST_NAME;

--3.
SELECT REGION_ID, REGION_NAME, SUBSTR(REGION_NAME, -1) AS "Last Letter in Region Name" FROM HR.REGIONS WHERE LENGTH(REGION_NAME) > 4 ORDER BY 3;

--4.
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, MOD(EMPLOYEE_ID, 4) + 1 AS "Team#" FROM HR.EMPLOYEES;

--5.
SELECT MOD(EMPLOYEE_ID, 4) + 1 AS "Team#", COUNT(EMPLOYEE_ID) AS "Employees on each Team" FROM HR.EMPLOYEES GROUP BY MOD(EMPLOYEE_ID, 4) + 1 ORDER BY 1;

--6.
SELECT TO_CHAR(START_DATE,'YYYY') AS "Year" , COUNT (*) AS "Number of Employees" FROM HR.JOB_HISTORY GROUP BY TO_CHAR(START_DATE,'YYYY') ORDER BY 1;

--7.
SELECT JOB_ID, TO_CHAR(AVG(SALARY), '$999,999.99') AS "Average Salary", COUNT(JOB_ID) AS "Total" FROM HR.EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY) > 10000 AND COUNT(JOB_ID) > 1;

--8.
SELECT REGION_NAME FROM HR.REGIONS NATURAL JOIN HR.COUNTRIES WHERE COUNTRY_NAME = 'Canada';

--9.
SELECT DISTINCT MANAGER_ID FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (20,30)
MINUS
SELECT DISTINCT MANAGER_ID FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (50)
ORDER BY MANAGER_ID;

--10.
SELECT ('Administrative Team Member: ' || SUBSTR(FIRST_NAME, 1, 1) || '.' || ' ' || LAST_NAME) AS "Initial and Last Name" FROM HR.EMPLOYEES WHERE JOB_ID LIKE 'AD%' ORDER BY 1;

--11.
SELECT TO_CHAR(((365*24*60*60*3) + (366*24*60*60))/4, '99G999G999') AS "Seconds in a year" FROM DUAL;

--12.
SELECT 
TO_CHAR(TO_DATE('2001-07-20 10:40:12', 'YYYY-MM-DD HH:MI:SS') - 2, 'DD-Mon-YY HH24:MI:SS') AS "Subtract 2 Days", 
TO_CHAR(TO_DATE('2001-07-20 10:40:12', 'YYYY-MM-DD HH:MI:SS') + 1/2, 'DD-Mon-YY HH24:MI:SS') AS "Add Half a Day",
TO_CHAR(TO_DATE('2001-07-20 10:40:12', 'YYYY-MM-DD HH:MI:SS') + 4.5/24, 'DD-Mon-YY HH24:MI:SS') AS "Add 4 and a Half Hours"
FROM DUAL;

--13.
SELECT TO_CHAR(TO_DATE('2015-May-13', 'YYYY-MON-DD'), 'Day, Mon YYYY') AS "Formatted Current Date" FROM DUAL;

--14.
SELECT 
ROUND(9.58348, 0) AS "Answer 1",
ROUND(9.58348, 1) AS "Answer 1_1",
ROUND(9.58348, 4) AS "Answer 3",
ROUND(9.58348, 5) AS "Answer 2"
FROM DUAL;

--15.
SELECT FLOOR(MONTHS_BETWEEN(TO_DATE('15-AUG-2011'), TO_DATE('4-DEC-1865')) /12) AS "Number of Years" FROM DUAL;

--16.
SELECT LAST_DAY(SYSDATE) AS "Last Day of Month" FROM DUAL;

--17.
SELECT COURSE_NO, DESCRIPTION,
CASE
    WHEN COST <= 1095 THEN 'Low'
    WHEN COST <= 1195 THEN 'Medium'
    WHEN COST <= 1595 THEN 'High'
END AS "Category for Costs"
FROM STUDENT.COURSE ORDER BY 3;
